spring:
  datasource: 
   url: jdbc:mysql://localhost:3306/college
   username: root
   password: sravani123
  application:
     name: DEPARTMENT 
   
server :
 port  : 8081
 
 
 
eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka
    
    
   instance: 
    hostname: localhost
    